const userTypes = {
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  SIGN_UP_SUCCES: 'SIGN_UP_SUCCES',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
  SIGN_OUT_USER_SUCCES: 'SIGN_OUT_USER_SUCCES',
  SIGN_UP_USER_START: 'SIGN_UP_USER_START',

  USER_ERROR: 'USER_ERROR',

  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_IN_SUCCES: 'SIGN_IN_SUCCES',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  RESET_PASSWORD_SUCCES: 'RESET_PASSWORD_SUCCES',
  RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
  RESET_AUTH_FORMS: 'RESET_AUTH_FORMS',
};

export default userTypes;
